language: ruby

sudo: false

rvm:
  - 2.2.3

env:
  - DB=postgresql

before_script:
  - psql -c 'create database classroom_test;' -U postgres

script:
  - ./script/cibuild

bundler_args: --without development production --deployment --jobs=3 --retry=3

notifications:
  email: false

env:
  - GITHUB_CLIENT_ID=client_id
