# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  github_client_id:     <%= ENV['GITHUB_CLIENT_ID']     %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>

development:
  <<: *default
  secret_key_base: 543ce28b5bbe8a2219a2872f0381c8fa16944916daa06d4cbe11761658a8df3406c43051f824f7820a86ed42916d05c5dca465b207a5f463ade0b94196a5fb24

test:
  <<: *default
  secret_key_base: ebddbf0015a89ec20d6ed6c049a0718f330b963e207ce18cb2d917ec7e3caaee1fa10cf9f8a0635e47c982e7410691dfb17f46f6a948a7f17b07a9de73e351c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
